apiVersion: v1
kind: Pod
metadata:
  name: next-pod
  labels:
    app: front-end
spec:
  containers:
    - name: dockerized-next
      image: dockerized-next
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
