apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
spec:
  type: NodePort
  ports:
    - name: "cleint-service"
      nodePort: 30000
      targetPort: 80
      port: 3000
  selector:
    app: client-app
    tier: front-end
