apiVersion: apps/v1
kind: Deployment

metadata:
  name: client
  labels:
    app: client-app
    tier: front-end
spec:
  replicas: 3
  template:
    metadata:
      name: client
      labels:
        app: client-app
        tier: front-end
    spec:
      containers:
        - name: client
          image: client
          imagePullPolicy: IfNotPresent
  selector:
    matchLabels:
      tier: front-end
