apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
    tier: back-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      name: server
      labels:
        app: server
        tier: back-end
    spec:
      containers:
        - image: server
          name: server
          imagePullPolicy: IfNotPresent
